spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:bativio}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER:bativio}
    password: ${PGPASSWORD:bativio}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: never

logging:
  level:
    com.bativio: DEBUG
    org.springframework.security: DEBUG
