export const defaultPrestations: Record<
  string,
  Array<{
    designation: string;
    unite: string;
    prixUnitaire: number;
    categorie: string;
    inclutFourniture: boolean;
  }>
> = {
  plombier: [
    {
      designation: "Depannage plomberie (intervention urgente)",
      unite: "forfait",
      prixUnitaire: 120,
      categorie: "Depannage",
      inclutFourniture: false,
    },
    {
      designation: "Debouchage canalisation",
      unite: "forfait",
      prixUnitaire: 150,
      categorie: "Depannage",
      inclutFourniture: false,
    },
    {
      designation: "Remplacement robinet mitigeur",
      unite: "unite",
      prixUnitaire: 180,
      categorie: "Robinetterie",
      inclutFourniture: true,
    },
    {
      designation: "Pose WC complet (fourniture + pose)",
      unite: "unite",
      prixUnitaire: 450,
      categorie: "Sanitaires",
      inclutFourniture: true,
    },
    {
      designation: "Pose lavabo avec robinetterie",
      unite: "unite",
      prixUnitaire: 350,
      categorie: "Sanitaires",
      inclutFourniture: true,
    },
    {
      designation: "Creation douche italienne complete",
      unite: "forfait",
      prixUnitaire: 3500,
      categorie: "Salle de bain",
      inclutFourniture: true,
    },
    {
      designation: "Pose baignoire avec robinetterie",
      unite: "unite",
      prixUnitaire: 800,
      categorie: "Salle de bain",
      inclutFourniture: true,
    },
    {
      designation: "Remplacement chauffe-eau electrique 200L",
      unite: "unite",
      prixUnitaire: 950,
      categorie: "Eau chaude",
      inclutFourniture: true,
    },
    {
      designation: "Creation alimentation eau (cuivre/PER)",
      unite: "ml",
      prixUnitaire: 55,
      categorie: "Tuyauterie",
      inclutFourniture: true,
    },
    {
      designation: "Creation evacuation PVC",
      unite: "ml",
      prixUnitaire: 45,
      categorie: "Tuyauterie",
      inclutFourniture: true,
    },
    {
      designation: "Renovation plomberie salle de bain complete",
      unite: "forfait",
      prixUnitaire: 5500,
      categorie: "Salle de bain",
      inclutFourniture: true,
    },
    {
      designation: "Depose sanitaires existants",
      unite: "unite",
      prixUnitaire: 80,
      categorie: "Depose",
      inclutFourniture: false,
    },
  ],

  electricien: [
    {
      designation: "Pose prise electrique (encastree)",
      unite: "unite",
      prixUnitaire: 85,
      categorie: "Prises",
      inclutFourniture: true,
    },
    {
      designation: "Remplacement tableau electrique",
      unite: "forfait",
      prixUnitaire: 1200,
      categorie: "Tableau",
      inclutFourniture: true,
    },
    {
      designation: "Mise aux normes NF C 15-100",
      unite: "forfait",
      prixUnitaire: 2500,
      categorie: "Normes",
      inclutFourniture: true,
    },
    {
      designation: "Passage de cable encastre",
      unite: "ml",
      prixUnitaire: 25,
      categorie: "Cablage",
      inclutFourniture: true,
    },
    {
      designation: "Pose spot encastre LED",
      unite: "unite",
      prixUnitaire: 75,
      categorie: "Eclairage",
      inclutFourniture: true,
    },
    {
      designation: "Installation VMC simple flux",
      unite: "forfait",
      prixUnitaire: 650,
      categorie: "Ventilation",
      inclutFourniture: true,
    },
    {
      designation: "Pose interrupteur / va-et-vient",
      unite: "unite",
      prixUnitaire: 70,
      categorie: "Interrupteurs",
      inclutFourniture: true,
    },
    {
      designation: "Pose prise de courant 16A",
      unite: "unite",
      prixUnitaire: 80,
      categorie: "Prises",
      inclutFourniture: true,
    },
    {
      designation: "Depannage electrique (diagnostic + reparation)",
      unite: "forfait",
      prixUnitaire: 130,
      categorie: "Depannage",
      inclutFourniture: false,
    },
    {
      designation: "Installation electrique piece complete",
      unite: "piece",
      prixUnitaire: 900,
      categorie: "Installation",
      inclutFourniture: true,
    },
  ],

  peintre: [
    {
      designation: "Peinture mur en bon etat (2 couches)",
      unite: "m2",
      prixUnitaire: 28,
      categorie: "Peinture murale",
      inclutFourniture: true,
    },
    {
      designation: "Peinture mur avec rebouchage + enduit",
      unite: "m2",
      prixUnitaire: 38,
      categorie: "Peinture murale",
      inclutFourniture: true,
    },
    {
      designation: "Peinture plafond (2 couches)",
      unite: "m2",
      prixUnitaire: 32,
      categorie: "Plafond",
      inclutFourniture: true,
    },
    {
      designation: "Decollage papier peint existant",
      unite: "m2",
      prixUnitaire: 12,
      categorie: "Preparation",
      inclutFourniture: false,
    },
    {
      designation: "Pose papier peint (fourni par client)",
      unite: "m2",
      prixUnitaire: 22,
      categorie: "Papier peint",
      inclutFourniture: false,
    },
    {
      designation: "Peinture boiseries / portes",
      unite: "unite",
      prixUnitaire: 95,
      categorie: "Boiseries",
      inclutFourniture: true,
    },
    {
      designation: "Enduit decoratif (beton cire, stuc, etc.)",
      unite: "m2",
      prixUnitaire: 65,
      categorie: "Decoration",
      inclutFourniture: true,
    },
    {
      designation: "Protection sols et meubles avant travaux",
      unite: "forfait",
      prixUnitaire: 80,
      categorie: "Preparation",
      inclutFourniture: true,
    },
  ],

  macon: [
    {
      designation: "Construction mur en parpaings",
      unite: "m2",
      prixUnitaire: 110,
      categorie: "Maconnerie",
      inclutFourniture: true,
    },
    {
      designation: "Coulage dalle beton (ep. 12-15 cm)",
      unite: "m2",
      prixUnitaire: 85,
      categorie: "Dalle",
      inclutFourniture: true,
    },
    {
      designation: "Chape de ragreage",
      unite: "m2",
      prixUnitaire: 35,
      categorie: "Chape",
      inclutFourniture: true,
    },
    {
      designation: "Ouverture mur porteur (IPN fourni + pose)",
      unite: "forfait",
      prixUnitaire: 2800,
      categorie: "Ouverture",
      inclutFourniture: true,
    },
    {
      designation: "Demolition cloison / mur non porteur",
      unite: "m2",
      prixUnitaire: 45,
      categorie: "Demolition",
      inclutFourniture: false,
    },
    {
      designation: "Fondations semelle filante",
      unite: "ml",
      prixUnitaire: 150,
      categorie: "Fondations",
      inclutFourniture: true,
    },
  ],

  carreleur: [
    {
      designation: "Pose carrelage sol (format standard 30x30 a 45x45)",
      unite: "m2",
      prixUnitaire: 55,
      categorie: "Sol",
      inclutFourniture: false,
    },
    {
      designation: "Pose carrelage grand format (60x60 et +)",
      unite: "m2",
      prixUnitaire: 70,
      categorie: "Sol",
      inclutFourniture: false,
    },
    {
      designation: "Pose faience murale",
      unite: "m2",
      prixUnitaire: 60,
      categorie: "Mural",
      inclutFourniture: false,
    },
    {
      designation: "Pose mosaique",
      unite: "m2",
      prixUnitaire: 90,
      categorie: "Mosaique",
      inclutFourniture: false,
    },
    {
      designation: "Depose carrelage existant",
      unite: "m2",
      prixUnitaire: 25,
      categorie: "Depose",
      inclutFourniture: false,
    },
    {
      designation: "Ragreage sol avant pose",
      unite: "m2",
      prixUnitaire: 20,
      categorie: "Preparation",
      inclutFourniture: true,
    },
  ],
};
