export const defaultPrestations: Record<
  string,
  Array<{
    designation: string;
    unite: string;
    prixUnitaire: number;
    categorie: string;
    inclutFourniture: boolean;
  }>
> = {
  plombier: [
    {
      designation: "Depannage plomberie (intervention urgente)",
      unite: "forfait",
      prixUnitaire: 120,
      categorie: "Depannage",
      inclutFourniture: false,
    },
    {
      designation: "Debouchage canalisation",
      unite: "forfait",
      prixUnitaire: 150,
      categorie: "Depannage",
      inclutFourniture: false,
    },
    {
      designation: "Remplacement robinet mitigeur",
      unite: "unite",
      prixUnitaire: 180,
      categorie: "Robinetterie",
      inclutFourniture: true,
    },
    {
      designation: "Pose WC complet (fourniture + pose)",
      unite: "unite",
      prixUnitaire: 450,
      categorie: "Sanitaires",
      inclutFourniture: true,
    },
    {
      designation: "Pose lavabo avec robinetterie",
      unite: "unite",
      prixUnitaire: 350,
      categorie: "Sanitaires",
      inclutFourniture: true,
    },
    {
      designation: "Creation douche italienne complete",
      unite: "forfait",
      prixUnitaire: 3500,
      categorie: "Salle de bain",
      inclutFourniture: true,
    },
    {
      designation: "Pose baignoire avec robinetterie",
      unite: "unite",
      prixUnitaire: 800,
      categorie: "Salle de bain",
      inclutFourniture: true,
    },
    {
      designation: "Remplacement chauffe-eau electrique 200L",
      unite: "unite",
      prixUnitaire: 950,
      categorie: "Eau chaude",
      inclutFourniture: true,
    },
    {
      designation: "Creation alimentation eau (cuivre/PER)",
      unite: "ml",
      prixUnitaire: 55,
      categorie: "Tuyauterie",
      inclutFourniture: true,
    },
    {
      designation: "Creation evacuation PVC",
      unite: "ml",
      prixUnitaire: 45,
      categorie: "Tuyauterie",
      inclutFourniture: true,
    },
    {
      designation: "Renovation plomberie salle de bain complete",
      unite: "forfait",
      prixUnitaire: 5500,
      categorie: "Salle de bain",
      inclutFourniture: true,
    },
    {
      designation: "Depose sanitaires existants",
      unite: "unite",
      prixUnitaire: 80,
      categorie: "Depose",
      inclutFourniture: false,
    },
  ],

  electricien: [
    {
      designation: "Pose prise electrique (encastree)",
      unite: "unite",
      prixUnitaire: 85,
      categorie: "Prises",
      inclutFourniture: true,
    },
    {
      designation: "Remplacement tableau electrique",
      unite: "forfait",
      prixUnitaire: 1200,
      categorie: "Tableau",
      inclutFourniture: true,
    },
    {
      designation: "Mise aux normes NF C 15-100",
      unite: "forfait",
      prixUnitaire: 2500,
      categorie: "Normes",
      inclutFourniture: true,
    },
    {
      designation: "Passage de cable encastre",
      unite: "ml",
      prixUnitaire: 25,
      categorie: "Cablage",
      inclutFourniture: true,
    },
    {
      designation: "Pose spot encastre LED",
      unite: "unite",
      prixUnitaire: 75,
      categorie: "Eclairage",
      inclutFourniture: true,
    },
    {
      designation: "Installation VMC simple flux",
      unite: "forfait",
      prixUnitaire: 650,
      categorie: "Ventilation",
      inclutFourniture: true,
    },
    {
      designation: "Pose interrupteur / va-et-vient",
      unite: "unite",
      prixUnitaire: 70,
      categorie: "Interrupteurs",
      inclutFourniture: true,
    },
    {
      designation: "Pose prise de courant 16A",
      unite: "unite",
      prixUnitaire: 80,
      categorie: "Prises",
      inclutFourniture: true,
    },
    {
      designation: "Depannage electrique (diagnostic + reparation)",
      unite: "forfait",
      prixUnitaire: 130,
      categorie: "Depannage",
      inclutFourniture: false,
    },
    {
      designation: "Installation electrique piece complete",
      unite: "piece",
      prixUnitaire: 900,
      categorie: "Installation",
      inclutFourniture: true,
    },
  ],

  peintre: [
    {
      designation: "Peinture mur en bon etat (2 couches)",
      unite: "m2",
      prixUnitaire: 28,
      categorie: "Peinture murale",
      inclutFourniture: true,
    },
    {
      designation: "Peinture mur avec rebouchage + enduit",
      unite: "m2",
      prixUnitaire: 38,
      categorie: "Peinture murale",
      inclutFourniture: true,
    },
    {
      designation: "Peinture plafond (2 couches)",
      unite: "m2",
      prixUnitaire: 32,
      categorie: "Plafond",
      inclutFourniture: true,
    },
    {
      designation: "Decollage papier peint existant",
      unite: "m2",
      prixUnitaire: 12,
      categorie: "Preparation",
      inclutFourniture: false,
    },
    {
      designation: "Pose papier peint (fourni par client)",
      unite: "m2",
      prixUnitaire: 22,
      categorie: "Papier peint",
      inclutFourniture: false,
    },
    {
      designation: "Peinture boiseries / portes",
      unite: "unite",
      prixUnitaire: 95,
      categorie: "Boiseries",
      inclutFourniture: true,
    },
    {
      designation: "Enduit decoratif (beton cire, stuc, etc.)",
      unite: "m2",
      prixUnitaire: 65,
      categorie: "Decoration",
      inclutFourniture: true,
    },
    {
      designation: "Protection sols et meubles avant travaux",
      unite: "forfait",
      prixUnitaire: 80,
      categorie: "Preparation",
      inclutFourniture: true,
    },
  ],

  macon: [
    {
      designation: "Construction mur en parpaings",
      unite: "m2",
      prixUnitaire: 110,
      categorie: "Maconnerie",
      inclutFourniture: true,
    },
    {
      designation: "Coulage dalle beton (ep. 12-15 cm)",
      unite: "m2",
      prixUnitaire: 85,
      categorie: "Dalle",
      inclutFourniture: true,
    },
    {
      designation: "Chape de ragreage",
      unite: "m2",
      prixUnitaire: 35,
      categorie: "Chape",
      inclutFourniture: true,
    },
    {
      designation: "Ouverture mur porteur (IPN fourni + pose)",
      unite: "forfait",
      prixUnitaire: 2800,
      categorie: "Ouverture",
      inclutFourniture: true,
    },
    {
      designation: "Demolition cloison / mur non porteur",
      unite: "m2",
      prixUnitaire: 45,
      categorie: "Demolition",
      inclutFourniture: false,
    },
    {
      designation: "Fondations semelle filante",
      unite: "ml",
      prixUnitaire: 150,
      categorie: "Fondations",
      inclutFourniture: true,
    },
  ],

  carreleur: [
    {
      designation: "Pose carrelage sol (format standard 30x30 a 45x45)",
      unite: "m2",
      prixUnitaire: 55,
      categorie: "Sol",
      inclutFourniture: false,
    },
    {
      designation: "Pose carrelage grand format (60x60 et +)",
      unite: "m2",
      prixUnitaire: 70,
      categorie: "Sol",
      inclutFourniture: false,
    },
    {
      designation: "Pose faience murale",
      unite: "m2",
      prixUnitaire: 60,
      categorie: "Mural",
      inclutFourniture: false,
    },
    {
      designation: "Pose mosaique",
      unite: "m2",
      prixUnitaire: 90,
      categorie: "Mosaique",
      inclutFourniture: false,
    },
    {
      designation: "Depose carrelage existant",
      unite: "m2",
      prixUnitaire: 25,
      categorie: "Depose",
      inclutFourniture: false,
    },
    {
      designation: "Ragreage sol avant pose",
      unite: "m2",
      prixUnitaire: 20,
      categorie: "Preparation",
      inclutFourniture: true,
    },
  ],
};

// Additional metiers added automatically
Object.assign(defaultPrestations, {
  chauffagiste: [
    { designation: "Installation chaudiere gaz", unite: "u", prixUnitaire: 1200, categorie: "Chaudiere", inclutFourniture: false },
    { designation: "Entretien annuel chaudiere", unite: "u", prixUnitaire: 120, categorie: "Entretien", inclutFourniture: true },
    { designation: "Installation pompe a chaleur", unite: "u", prixUnitaire: 3500, categorie: "PAC", inclutFourniture: false },
    { designation: "Pose radiateur", unite: "u", prixUnitaire: 250, categorie: "Radiateur", inclutFourniture: false },
    { designation: "Pose plancher chauffant", unite: "m2", prixUnitaire: 65, categorie: "Plancher chauffant", inclutFourniture: true },
    { designation: "Desembouage circuit chauffage", unite: "u", prixUnitaire: 350, categorie: "Entretien", inclutFourniture: true },
    { designation: "Main d'oeuvre", unite: "h", prixUnitaire: 55, categorie: "Main d'oeuvre", inclutFourniture: false },
  ],
  menuisier: [
    { designation: "Pose porte interieure", unite: "u", prixUnitaire: 250, categorie: "Portes", inclutFourniture: false },
    { designation: "Pose fenetre PVC", unite: "u", prixUnitaire: 450, categorie: "Fenetres", inclutFourniture: false },
    { designation: "Pose parquet flottant", unite: "m2", prixUnitaire: 30, categorie: "Parquet", inclutFourniture: false },
    { designation: "Placard sur mesure", unite: "ml", prixUnitaire: 350, categorie: "Rangement", inclutFourniture: true },
    { designation: "Pose cuisine equipee", unite: "ml", prixUnitaire: 200, categorie: "Cuisine", inclutFourniture: false },
    { designation: "Main d'oeuvre", unite: "h", prixUnitaire: 45, categorie: "Main d'oeuvre", inclutFourniture: false },
  ],
  couvreur: [
    { designation: "Refection toiture tuiles", unite: "m2", prixUnitaire: 80, categorie: "Toiture", inclutFourniture: true },
    { designation: "Reparation fuite toiture", unite: "u", prixUnitaire: 350, categorie: "Depannage", inclutFourniture: true },
    { designation: "Demoussage toiture", unite: "m2", prixUnitaire: 15, categorie: "Entretien", inclutFourniture: true },
    { designation: "Pose gouttiere alu", unite: "ml", prixUnitaire: 45, categorie: "Gouttiere", inclutFourniture: true },
    { designation: "Isolation combles", unite: "m2", prixUnitaire: 40, categorie: "Isolation", inclutFourniture: true },
    { designation: "Pose velux", unite: "u", prixUnitaire: 800, categorie: "Fenetre de toit", inclutFourniture: false },
    { designation: "Main d'oeuvre", unite: "h", prixUnitaire: 50, categorie: "Main d'oeuvre", inclutFourniture: false },
  ],
  serrurier: [
    { designation: "Ouverture porte claquee", unite: "u", prixUnitaire: 90, categorie: "Depannage", inclutFourniture: false },
    { designation: "Ouverture porte blindee", unite: "u", prixUnitaire: 180, categorie: "Depannage", inclutFourniture: false },
    { designation: "Changement serrure 3 points", unite: "u", prixUnitaire: 280, categorie: "Serrure", inclutFourniture: true },
    { designation: "Pose porte blindee", unite: "u", prixUnitaire: 1500, categorie: "Porte blindee", inclutFourniture: false },
    { designation: "Remplacement cylindre", unite: "u", prixUnitaire: 120, categorie: "Serrure", inclutFourniture: true },
    { designation: "Deplacement", unite: "u", prixUnitaire: 40, categorie: "Frais", inclutFourniture: false },
  ],
  cuisiniste: [
    { designation: "Pose cuisine equipee complete", unite: "ml", prixUnitaire: 250, categorie: "Pose", inclutFourniture: false },
    { designation: "Raccordement eau", unite: "u", prixUnitaire: 150, categorie: "Plomberie", inclutFourniture: true },
    { designation: "Raccordement electrique", unite: "u", prixUnitaire: 120, categorie: "Electricite", inclutFourniture: true },
    { designation: "Pose plan de travail", unite: "ml", prixUnitaire: 80, categorie: "Plan de travail", inclutFourniture: false },
    { designation: "Pose credence", unite: "ml", prixUnitaire: 60, categorie: "Credence", inclutFourniture: false },
    { designation: "Main d'oeuvre", unite: "h", prixUnitaire: 45, categorie: "Main d'oeuvre", inclutFourniture: false },
  ],
  "reparation-mobile": [
    { designation: "Remplacement \u00e9cran iPhone", unite: "u", prixUnitaire: 89, categorie: "\u00c9cran", inclutFourniture: true },
    { designation: "Remplacement \u00e9cran Samsung", unite: "u", prixUnitaire: 79, categorie: "\u00c9cran", inclutFourniture: true },
    { designation: "Remplacement batterie iPhone", unite: "u", prixUnitaire: 49, categorie: "Batterie", inclutFourniture: true },
    { designation: "Remplacement batterie Samsung", unite: "u", prixUnitaire: 39, categorie: "Batterie", inclutFourniture: true },
    { designation: "Connecteur de charge", unite: "u", prixUnitaire: 45, categorie: "Connecteur", inclutFourniture: true },
    { designation: "Bouton home / power", unite: "u", prixUnitaire: 35, categorie: "Boutons", inclutFourniture: true },
    { designation: "Cam\u00e9ra avant / arri\u00e8re", unite: "u", prixUnitaire: 55, categorie: "Cam\u00e9ra", inclutFourniture: true },
    { designation: "Haut-parleur / micro", unite: "u", prixUnitaire: 35, categorie: "Audio", inclutFourniture: true },
    { designation: "Diagnostic complet", unite: "u", prixUnitaire: 0, categorie: "Diagnostic", inclutFourniture: false },
    { designation: "D\u00e9blocage logiciel", unite: "u", prixUnitaire: 29, categorie: "Logiciel", inclutFourniture: false },
  ],
});
